(package "auto-scroll-bar"
         "0.1.1"
         "Automatically show/hide scroll-bars as needed")

(website-url "https://github.com/jcs-elpa/auto-scroll-bar")
(keywords "convenience" "scrollbar")

(package-file "auto-scroll-bar.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "27.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
